### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: /tmp/opencv_openpnp5364447482759473585/nu/pattern/opencv/linux/x86_64/libopencv_java460.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/opencv_openpnp5364447482759473585/nu/pattern/opencv/linux/x86_64/libopencv_java460.so)

### ISSUE THREAD

**Issue by tiandaye** [openpnp/opencv#108]
hi,Could you please take a look at my question, Thank you.

The mac system runs properly, but centos7 runs abnormally. The error message is as follows

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opencv.ml.SVM]: Factory method 'svm' threw exception with message: /tmp/opencv_openpnp2647728894578271542/nu/pattern/opencv/linux/x86_64/libopencv_java481.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/opencv_openpnp2647728894578271542/nu/pattern/opencv/linux/x86_64/libopencv_java481.so)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.4.jar!/:6.0.4]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.0.4.jar!/:6.0.4]
        ... 27 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/opencv_openpnp2647728894578271542/nu/pattern/opencv/linux/x86_64/libopencv_java481.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/opencv_openpnp2647728894578271542/nu/pattern/opencv/linux/x86_64/libopencv_java481.so)
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
        at java.lang.System.load(System.java:1953) ~[?:?]
        at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:330) ~[opencv-4.8.1-0.jar!/:?]
        at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:326) ~[opencv-4.8.1-0.jar!/:?]
        at nu.pattern.OpenCV$LocalLoader$Holder.<clinit>(OpenCV.java:336) ~[opencv-4.8.1-0.jar!/:?]
        at nu.pattern.OpenCV$LocalLoader.getInstance(OpenCV.java:340) ~[opencv-4.8.1-0.jar!/:?]
        at nu.pattern.OpenCV.loadLocally(OpenCV.java:323) ~[opencv-4.8.1-0.jar!/:?]
        at com.tian.www.config.OpenCVConfig.svm(OpenCVConfig.java:34) ~[classes!/:1.0-SNAPSHOT]
        at com.tian.www.config.OpenCVConfig$$SpringCGLIB$$0.CGLIB$svm$0(<generated>) ~[classes!/:1.0-SNAPSHOT]
        at com.tian.www.config.OpenCVConfig$$SpringCGLIB$$2.invoke(<generated>) ~[classes!/:1.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.4.jar!/:6.0.4]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.4.jar!/:6.0.4]
        at com.tian.www.config.OpenCVConfig$$SpringCGLIB$$0.svm(<generated>) ~[classes!/:1.0-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.4.jar!/:6.0.4]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.0.4.jar!/:6.0.4]
        ... 27 more
```

my code:

```
nu.pattern.OpenCV.loadLocally();
```

maven config:

```
<dependency>
    <groupId>org.openpnp</groupId>
    <artifactId>opencv</artifactId>
    <version>4.8.1-0</version>
</dependency>
```

System Information:

```
$ java --version
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ uname -m && cat /etc/*release
x86_64
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
```

**Comment by thomedw** [comment]
Hi,

I think the distribution is not supported. The opencv was build with ubuntu 20 using glibc 2.27. You might need to upgrade the glibc or install compatibility layer.

**Comment by tiandaye** [comment]
> Hi,
> 
> I think the distribution is not supported. The opencv was build with ubuntu 20 using glibc 2.27. You might need to upgrade the glibc or install compatibility layer.

Thank you
