### ISSUE TITLE
CascadeClassifier exception

### ISSUE THREAD

**Issue by virl** [openpnp/opencv#17]
"Unrecognized or unsupported array type in function cvGetMat":
```
Caused by: CvException [org.opencv.core.CvException: cv::Exception: /Users/jason/Projects/openpnp/opencv/opencv/opencv-3.2.0/modules/core/src/array.cpp:2501: error: (-206) Unrecognized or unsupported array type in function cvGetMat
]
	at org.opencv.objdetect.CascadeClassifier.detectMultiScale_1(Native Method)
	at org.opencv.objdetect.CascadeClassifier.detectMultiScale(CascadeClassifier.java:159)
```
Source (Kotlin):
```
val faceGrayMat = gray.submat(faceRect)
var drects = MatOfRect()
eyeLeftCascade.detectMultiScale(faceGrayMat, drects)
```
What is strange is that that code has been called thousands of times for the images of the same format, but the exception occurs only from time to time.

**Comment by virl** [comment]
Maybe I wrongly construct Mat()?
```
val gray = Mat(image.height, image.width, ImageUtil.colorModelToCvType(image.colorModel))
```
Does the cols and rows correspond to image width and height? Or are they must be multiplied by the channels?

**Comment by vonnieda** [comment]
Hi @virl, I suggest you post this to the OpenCV issues list at https://github.com/opencv/opencv. This project is little more than just a packaging of the OpenCV bindings. The change you are looking for would have to be on OpenCV itself.
