### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.opencv.videoio.VideoCapture.VideoCapture_2(I)J

### ISSUE THREAD

**Issue by arungoyal** [openpnp/opencv#34]
Hi

I am facing below issue while running a sample code, just accessing VideoCapture instance.
java.lang.UnsatisfiedLinkError: org.opencv.videoio.VideoCapture.VideoCapture_2(I)J

I am working on Ubuntu and have open CV 3.4 installed properly.
I already set all class paths in environment variables as below : 

OPENCV_HOME="/home/.../softwares/opencv-3.2.0/"
OPENCV_LIB="/home/.../softwares/opencv-3.2.0/build/lib"
OPENCV_JAR="/home/.../softwares/opencv-3.2.0/build/bin/opencv-320.jar"

I followed all the step for adding library in eclipse, whether it is by adding user library or by adding jar files. I followed [](https://github.com/bytedeco/javacv/issues/496) for JNI.

I tried a lot. 

Let me know what is issue or what i am missing .

Thanks
Arun

**Comment by vonnieda** [comment]
Hi @arungoyal, can you please post the full error + stack trace?

**Comment by arungoyal** [comment]
Hi

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.videoio.VideoCapture.VideoCapture_2(I)J
	at org.opencv.videoio.VideoCapture.VideoCapture_2(Native Method)
	at org.opencv.videoio.VideoCapture.<init>(VideoCapture.java:54)
	at com.example.demo.Hello.main(Hello.java:16)

above is the full stack trace
I also attached a sample java class as well.
[Hello.txt](https://github.com/openpnp/opencv/files/2123111/Hello.txt)

Please let me know whats wrong with configuration.
Opencv is installed on system, i have checked using some commands on terminal
I am using eclipse and and tried on intellij IDEA as well, facing same issue.

Thanks
Arun

**Comment by vonnieda** [comment]
I've just released version 3.4.2-0, please try this and see if it resolves the issue.

**Comment by arungoyal** [comment]
Hi @vonnieda 

Thanks for replying. I'll check and let you know.

**Comment by stagging18** [comment]
Hi All,
I am facing the same issue with opencv_320.
While i am running the same code with eclipse it is working fine.
But while creating a fat jar of my project and running it from command line i am getting the below exception.

Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: org.opencv.videoio.VideoCapture.VideoCapture_3()J
        at org.opencv.videoio.VideoCapture.VideoCapture_3(Native Method)
        at org.opencv.videoio.VideoCapture.<init>(VideoCapture.java:68)
        at com.iot.video.app.kafka.collector.VideoEventGenerator.generateEvent(VideoEventGenerator.java:97)

Note: I have placed the DLL file inside my windows/system 32 directory.

Regards,
Rajesh
