### ISSUE TITLE
Unable to load on OS X / IntelliJ with either loadLocally() or loadShared()

### ISSUE THREAD

**Issue by salamanders** [openpnp/opencv#40]
Starting from Maven:

```
        <dependency>
            <groupId>org.openpnp</groupId>
            <artifactId>opencv</artifactId>
            <version>3.4.2-0</version>
        </dependency>

```

nu.pattern.OpenCV.loadShared()

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java343 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:208)
	at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:189)
	at nu.pattern.OpenCV$SharedLoader$Holder.<clinit>(OpenCV.java:229)
	at nu.pattern.OpenCV$SharedLoader.getInstance(OpenCV.java:233)
	at nu.pattern.OpenCV.loadShared(OpenCV.java:183)
	at src.main.kotlin.MainKt.main(Main.kt:27)
	at src.main.kotlin.MainKt.main(Main.kt)
```

nu.pattern.OpenCV.loadLocally()

```
/Library/Java/JavaVirtualMachines/default/Contents/Home/bin/java -Xmx12g "-javaagent:/Users/benhill/Applications/IntelliJ IDEA 2018.3 EAP.app/Contents/lib/idea_rt.jar=53128:/Users/benhill/Applications/IntelliJ IDEA 2018.3 EAP.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/default/Contents/Home/lib/tools.jar:/Users/benhill/Documents/workspace/facesnap/target/classes:/Users/benhill/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.0/kotlin-stdlib-jdk8-1.3.0.jar:/Users/benhill/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.3.0/kotlin-stdlib-1.3.0.jar:/Users/benhill/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0/kotlin-stdlib-common-1.3.0.jar:/Users/benhill/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/benhill/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.0/kotlin-stdlib-jdk7-1.3.0.jar:/Users/benhill/.m2/repository/org/bytedeco/javacv/1.4.3/javacv-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp/1.4.3/javacpp-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.11.3.121-1.4.3/flycapture-2.11.3.121-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.5-1.4.3/libdc1394-2.2.5-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.4.3/libfreenect-0.5.3-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/libfreenect2/0.2.0-1.4.3/libfreenect2-0.2.0-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.12.1-1.4.3/librealsense-1.12.1-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/videoinput/0.200-1.4.3/videoinput-0.200-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.4.3/artoolkitplus-2.3.1-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.4.3/flandmark-1.07-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.76.0-1.4.3/leptonica-1.76.0-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/tesseract/4.0.0-rc2-1.4.3/tesseract-4.0.0-rc2-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.3-1.4.3/opencv-3.4.3-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg-platform/4.0.2-1.4.3/ffmpeg-platform-4.0.2-1.4.3.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-android-arm.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-android-arm64.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-android-x86.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-android-x86_64.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-linux-x86.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-linux-x86_64.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-linux-armhf.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-linux-ppc64le.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-macosx-x86_64.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-windows-x86.jar:/Users/benhill/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/4.0.2-1.4.3/ffmpeg-4.0.2-1.4.3-windows-x86_64.jar:/Users/benhill/.m2/repository/org/openpnp/opencv/3.4.2-0/opencv-3.4.2-0.jar:/Users/benhill/.m2/repository/com/natpryce/konfig/1.6.10.0/konfig-1.6.10.0.jar:/Users/benhill/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.3.0/kotlin-reflect-1.3.0.jar:/Users/benhill/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar:/Users/benhill/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/benhill/.m2/repository/io/github/microutils/kotlin-logging/1.6.10/kotlin-logging-1.6.10.jar:/Users/benhill/.m2/repository/io/github/microutils/kotlin-logging-common/1.6.10/kotlin-logging-common-1.6.10.jar src.main.kotlin.MainKt
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/yf/n2ww6hgn0_vghpv9jb289pd8006t9p/T/opencv_openpnp6473975923817250546/nu/pattern/opencv/osx/x86_64/libopencv_java342.dylib: dlopen(/private/var/folders/yf/n2ww6hgn0_vghpv9jb289pd8006t9p/T/opencv_openpnp6473975923817250546/nu/pattern/opencv/osx/x86_64/libopencv_java342.dylib, 1): Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib
  Referenced from: /private/var/folders/yf/n2ww6hgn0_vghpv9jb289pd8006t9p/T/opencv_openpnp6473975923817250546/nu/pattern/opencv/osx/x86_64/libopencv_java342.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:298)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:294)
	at nu.pattern.OpenCV$LocalLoader$Holder.<clinit>(OpenCV.java:304)
	at nu.pattern.OpenCV$LocalLoader.getInstance(OpenCV.java:308)
	at nu.pattern.OpenCV.loadLocally(OpenCV.java:291)
	at src.main.kotlin.MainKt.main(Main.kt:27)
	at src.main.kotlin.MainKt.main(Main.kt)
```

Anything special I should be doing beyond the POM dependency?

**Comment by vonnieda** [comment]
@salamanders Are you using Java 10? See #33

**Comment by salamanders** [comment]
I didn't think I was - even though I have 10 on my system, I thought it was all executing with 1.8.
Removing 10 to be sure...
`println(System.getProperty("java.version"))` does return "1.8.0_181"

**Comment by salamanders** [comment]
I have, but I can try the older version.  (I was hoping to use 3.x)

```
ffmpeg -version
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with Apple LLVM version 10.0.0 (clang-1000.11.45.2)
configuration: --prefix=/Users/benhill/brew/homebrew/Cellar/ffmpeg/4.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gpl --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-librtmp --enable-libssh --enable-libvidstab --enable-libwebp --enable-opencl --enable-openssl --enable-videotoolbox --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/Users/benhill/brew/homebrew/Cellar/openjpeg/2.3.0/include/openjpeg-2.3 --enable-nonfree

```

**Comment by salamanders** [comment]
Two things of note:

1. My brew is under my user (so I don't have to run it as root)  `Warning: Your Homebrew's prefix is not /usr/local.`
2. This is Kotlin.  (which shouldn't matter, it is running java under the hood)

**Comment by vonnieda** [comment]
Oh, it looks like you are referring to the wrong project. In your pom you are referring to JavaCV. This project is OpenPnP OpenCV. The two are not related, and are not compatible. See https://github.com/bytedeco/javacv

**Comment by salamanders** [comment]
Sorry, fixed that!
Yes I'm using JavaCV for the video decoding.
But then I'm converting to a openCvMat so I can do face recognition.  (and trying to keep track of "which Mat")

and it dies with 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/yf/n2ww6hgn0_vghpv9jb289pd8006t9p/T/opencv_openpnp3509792775981883221/nu/pattern/opencv/osx/x86_64/libopencv_java342.dylib: dlopen(/private/var/folders/yf/n2ww6hgn0_vghpv9jb289pd8006t9p/T/opencv_openpnp3509792775981883221/nu/pattern/opencv/osx/x86_64/libopencv_java342.dylib, 1): Library not loaded: /usr/local/opt/ffmpeg/lib/libavformat.58.dylib
  Referenced from: /private/var/folders/yf/n2ww6hgn0_vghpv9jb289pd8006t9p/T/opencv_openpnp3509792775981883221/nu/pattern/opencv/osx/x86_64/libopencv_java342.dylib
  Reason: image not found
```

**Comment by salamanders** [comment]
PS: I tried a soft-link, I'm still suspicious that "my homebrew being local" could be the culprit.
But no luck there.
`sudo ln -s /Users/MYUSERNAME/brew/homebrew/lib/libavcodec.58.dylib /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib`

**Comment by salamanders** [comment]
Wow, it compiles and runs! I had to hack it: 
`sudo ln -s /Users/MYUSERNAME/brew/homebrew/Cellar/ffmpeg/4.1/lib /usr/local/opt/ffmpeg/lib`
so I'm very suspicious that someone somewhere doesn't play nice with homebrew installing in a local directory.

**Comment by vonnieda** [comment]
Glad you got it sorted @salamanders. I'm hoping to get #38 fixed this weekend so hopefully people won't have to jump through this hoop.
