### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no opencv_java320 in java.library.path running two Java VM's on the same Windows Server

### ISSUE THREAD

**Issue by michelriondel** [openpnp/opencv#48]
Hi 

We use your Maven Project and it runs very well. 
We use the Maven Project:
<dependency>
	<groupId>org.openpnp</groupId>
	<artifactId>opencv</artifactId>
	<version>3.2.0-0</version>
</dependency>
		
And Initialize the OpenCV Libraries like that
/**
 * Load the OpenCV Library once static
 */
	static {
		nu.pattern.OpenCV.loadShared();
	}

From the documentation on the github mainpage I understand, that when the vm starts it copies the libraries to some temp location. 
Could it be that if we start two Java VM's on the same Windows Server that there is some overriding? Or is there any other restriction? 

Basically the stacktrace we get is: 
2019-10-28 12:48:31,654 ERROR ch.helsana.unifygate.consumer.GenericConsumer [pool-1-thread-2] APP1_20190813_01469153: error on process <AdaptiveThresholdProcessor> - 
 ch.helsana.unifygate.processor.ProcessorException: java.lang.UnsatisfiedLinkError: no opencv_java320 in java.library.path
 at ch.helsana.unifygate.processor.AdaptiveThresholdProcessor.process(AdaptiveThresholdProcessor.java:115)
 at ch.helsana.unifygate.consumer.GenericConsumer.consume(GenericConsumer.java:35)
 at ch.helsana.unifygate.consumer.AbstractConsumer.run(AbstractConsumer.java:93)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.UnsatisfiedLinkError: no opencv_java320 in java.library.path
 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
 at java.lang.Runtime.loadLibrary0(Runtime.java:870)
 at java.lang.System.loadLibrary(System.java:1122)
 at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:204)
 at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:185)
 at nu.pattern.OpenCV$SharedLoader$Holder.<clinit>(OpenCV.java:225)
 at nu.pattern.OpenCV$SharedLoader.getInstance(OpenCV.java:229)
 at nu.pattern.OpenCV.loadShared(OpenCV.java:179)
 at ch.helsana.unifygate.utils.ImageUtils.<clinit>(ImageUtils.java:33)
 at ch.helsana.unifygate.processor.AdaptiveThresholdProcessor.createAdaptiveThresholdFile(AdaptiveThresholdProcessor.java:161)
 at ch.helsana.unifygate.processor.AdaptiveThresholdProcessor.process(AdaptiveThresholdProcessor.java:82)
 ... 5 common frames omitted

Any help on how to run multiple VM's on the same server would help. 

Regards Michel Riondel

**Comment by michelriondel** [comment]
Hi there

short update from my side.. If we copy the jar file that includes opencv to two locations and run those separate jar files we don't get any issues. I guess that is as described solving the temp directory problem. 

regards Michel Riondel

**Comment by vonnieda** [comment]
Thanks for the report @michelriondel. I bet that what is happening is that https://github.com/openpnp/opencv/blob/develop/src/main/java/nu/pattern/OpenCV.java#L377 causes the second instance to delete the files from the first. I hope to switch to a better native library loader in the future (https://github.com/openpnp/opencv/issues/44#issuecomment-511515533) and hopefully that would resolve this as well.

**Comment by vonnieda** [comment]
Please try the latest version and re-open if this is still relevant.
