### ISSUE TITLE
  CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.1) /Users/runner/work/opencv/opencv/opencv-4.5.1/modules/imgproc/src/templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'matchTemplate' ]

### ISSUE THREAD

**Issue by aman13garg** [openpnp/opencv#77]
at org.opencv.imgproc.Imgproc.matchTemplate_1(Native Method)
at org.opencv.imgproc.Imgproc.matchTemplate(Imgproc.java:7119)
at qa.justtestlah.visual.OpenCVTemplateMatcher.match(OpenCVTemplateMatcher.java:84)
at qa.justtestlah.visual.OpenCVTemplateMatcher.match(OpenCVTemplateMatcher.java:52)
at qa.justtestlah.base.BasePage.findImage(BasePage.java:143)
at qa.justtestlah.base.BasePage.hasImage(BasePage.java:102)
at qa.justtestlah.base.BasePage$$FastClassBySpringCGLIB$$6d0ee866.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
at test.pages.LoginPage$$EnhancerBySpringCGLIB$$dbe86848.hasImage(<generated>)

For MAC 11.0.1 , ios 14.5 and open jdk 11 it is working fine.

But when you change the OS to 11.2.3 , ios 14.5 and open jdk 11 same is failing with above exception. Can you help me to resolve the same ? Using 4.5.1 version.

**Comment by vonnieda** [comment]
Please try the latest version and re-open if this is still relevant.
