### ISSUE TITLE
Cannot load native library on Apple Silicon 

### ISSUE THREAD

**Issue by hrchu** [openpnp/opencv#84]
While loading the OpenCV native library by ` System.loadLibrary(Core.NATIVE_LIBRARY_NAME)`,`UnsatisfiedLinkError` occurred:
   
```
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java -javaagent:/Users/petertc/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=57480:/Users/petertc/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/petertc/workspace/s3-event-driven/play-opencv2/target/classes:/Users/petertc/.m2/repository/org/openpnp/opencv/4.5.5-1/opencv-4.5.5-1.jar org.example.HelloCV
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java455 in java.library.path: /Users/petertc/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.example.HelloCV.main(HelloCV.java:24)

```
openCV version: 4.5.5-1
JDK version: I've tried Java 8/17/19 and have the same issue.

**Comment by hrchu** [comment]
Just notice I should use `OpenCV.loadShared()`
